import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { createClient } from 'contentful'
import RecipeCard from '../../components/RecipeCard'

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps(){
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID, 
    accessToken: process.env.CONTENTFUL_ACCESS_KEY 
  })
  
  const res = await client.getEntries({content_type: 'recipe'})
  return{
    props: {
      recipes: res.items,
      revalidate: 1
    }
  }
}

export default function Home({recipes}) {
  //console.log(recipes)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=' bg-yellow-500 py-8 uppercase flex flex-col items-center'>
        <div className='text-3xl font-medium'>Just Add</div>
        <div className='text-6xl font-bold'>Marmite</div>
        <div className='font-semibold'>Spread the Joy</div>
      </div>
      
      <div className=' bg-yellow-500 grid md:grid-cols-2 lg:grid-cols-3 gap-16 md:px-[160px] px-[50px]'>
        {
          recipes.map(recipe=> (
            <RecipeCard key={recipe.sys.id} recipe={recipe}/>
          ))
        }
      </div>
    </>
  )
}
